Importamos el archivo csv con los datos de ventas

In [10]:
import pandas as pd
ventas_csv = pd.read_csv('/content/ventas.csv', encoding = "ISO-8859-1")

Le pedimos que nos muestre solo las primeras 5 lineas de datos de ventas

In [11]:
ventas_csv.head(5)

,venta_id,fecha,cliente_id,producto_id,producto,categoria,cantidad,precio_unitario,medio_pago,canal
0,V001,2026-08-01,C001,P001,Auriculares Bluetooth,Electronica,2,45990.0,Tarjeta,Web
1,V002,2026-08-02,C002,P004,Mochila urbana,Accesorios,1,38500.0,Transferencia,App
2,V003,2026-08-03,C003,P002,Mouse inalambrico,Electronica,3,18500.0,Billetera virtual,Web
3,V004,2026-08-04,C001,P006,Botella termica,Hogar,1,27990.0,Tarjeta,App
4,V005,2026-08-05,C004,P003,Teclado mecanico,Electronica,1,68990.0,Transferencia,Web

Importamos los datos de clientes desde el archivo JSON y mostramos la cantidad total de clientes.

In [8]:
import pandas as pd
clientes_json = pd.read_json('/content/clientes.json')
clientes_json

,cliente_id,nombre,edad,ciudad,email,fecha_registro,cliente_frecuente
0,C001,Sofia Martinez,29,Ushuaia,sofia.martinez@example.com,2025-11-12,True
1,C002,Lucas Gomez,35,Rio Grande,lucas.gomez@example.com,2026-01-08,True
2,C003,Valentina Perez,24,Ushuaia,valentina.perez@example.com,2026-02-17,False
3,C004,Mateo Rodriguez,41,Tolhuin,mateo.rodriguez@example.com,2025-09-03,True
4,C005,Camila Lopez,32,Rio Grande,camila.lopez@example.com,2026-03-21,False
5,C006,Joaquin Fernandez,27,Ushuaia,joaquin.fernandez@example.com,2026-04-10,False
6,C007,Martina Diaz,38,Rio Grande,martina.diaz@example.com,2025-12-05,True
7,C008,Benjamin Torres,30,Tolhuin,benjamin.torres@example.com,2026-05-14,False
8,C009,Julieta Sanchez,26,Ushuaia,julieta.sanchez@example.com,2026-06-02,False
9,C010,Tomas Alvarez,45,Rio Grande,tomas.alvarez@example.com,2025-10-19,True

Importamos los datos de inventario desde la hoja de cálculo Excel

In [14]:
import pandas as pd
inventario_excel = pd.read_excel('/content/inventario.xlsx', engine='openpyxl')
inventario_excel

,producto_id,producto,categoria,stock_actual,stock_minimo,precio_unitario,proveedor,ultima_actualizacion
0,P001,Auriculares Bluetooth,Electronica,35,10,45990,TecnoSur,2026-08-31
1,P002,Mouse inalambrico,Electronica,52,15,18500,TecnoSur,2026-08-31
2,P003,Teclado mecanico,Electronica,18,8,68990,Patagonia Digital,2026-08-30
3,P004,Mochila urbana,Accesorios,27,10,38500,Distribuidora Austral,2026-08-29
4,P005,Reloj inteligente,Electronica,12,5,89990,Patagonia Digital,2026-08-31
5,P006,Botella termica,Hogar,44,12,27990,Hogar del Sur,2026-08-28
6,P007,Set de organizadores,Hogar,21,8,19990,Hogar del Sur,2026-08-28
7,P008,Cuaderno premium,Libreria,65,20,8500,Papelera Fueguina,2026-08-27
8,P009,Cargador portatil,Electronica,29,10,35990,TecnoSur,2026-08-31
9,P010,Lampara de escritorio,Hogar,16,6,24900,Distribuidora Austral,2026-08-29

Calculamos el promedio de stock disponible para todos los productos.

In [15]:
stock_promedio = inventario_excel["stock_actual"].mean()

print("El promedio de stock disponible es:", stock_promedio)

El promedio de stock disponible es: 31.9